### ISSUE TITLE
Missing `--dump-input` flags

### ISSUE THREAD

**Issue by AntonLydike** [AntonLydike/filecheck#19]
Currently responsible for 14 / 69 remaining test failures:

- `mlir/test/Conversion/AsyncToLLVM/convert-runtime-to-llvm.mlir`
- `mlir/test/mlir-cpu-runner/async-error.mlir`
- `mlir/test/mlir-cpu-runner/async-func.mlir`
- `mlir/test/Dialect/Async/coro.mlir`
- `mlir/test/Dialect/Async/async-to-async-runtime.mlir`
- `mlir/test/mlir-cpu-runner/async-value.mlir`
- `mlir/test/Dialect/Async/async-parallel-for-async-dispatch.mlir`
- `mlir/test/Dialect/Async/runtime.mlir`
- `mlir/test/Dialect/ControlFlow/canonicalize.mlir`
- `mlir/test/Dialect/Math/algebraic-simplification.mlir`
- `mlir/test/Dialect/Async/async-parallel-for-num-worker-threads.mlir`
- `mlir/test/Dialect/Async/async-parallel-for-seq-dispatch.mlir`
- `mlir/test/Dialect/SCF/one-shot-bufferize-allow-return-allocs-no-deallocs.mlir`
- `mlir/test/Dialect/Shape/remove-shape-constraints.mlir`

**Comment by stanislaw** [comment]
The StrictDoc project now has all tests failing because of this, see https://github.com/strictdoc-project/strictdoc/pull/1921#issuecomment-2241164474.

> Integration tests fail because the recently released filecheck 1.0.0 [doesn't support --dump-input](https://github.com/AntonLydike/filecheck/issues/19). This is a regression unrelated to this PR.

**Comment by AntonLydike** [comment]
Thanks for the pointer! I will look into this tomorrow, I have an exam later today!

**Comment by AntonLydike** [comment]
Sorry I didn't get to it yet, there's currently a lot going on and I'm missing stuff on my to-do list. I'll try to get this done this week!

**Comment by stanislaw** [comment]
Many of the StrictDoc tests use ` | filecheck %s --dump-input=fail`.

This option doesn't change anything in how the checks are made. When it is activated, the full input provided/piped to filecheck is printed. This has been very useful for implementing the itests and debugging them in case of regressions.

P.S. I am still waiting for you to come back regarding the license topic. Please do not take too much time to consider it.

**Comment by AntonLydike** [comment]
> Many of the StrictDoc tests use ` | filecheck %s --dump-input=fail`.
> 
> This option doesn't change anything in how the checks are made. When it is activated, the full input provided/piped to filecheck is printed. This has been very useful for implementing the itests and debugging them in case of regressions.

Interesting! `fail` seems to be the default value for `--dump-input`, I'll think about the best way to proceed... I am unsure if the other options `never` (don't print error messages), `help` (kind of like `--help`, but for the output produced) and `always` (print the input to stderr if successful) are particularly useful modes, to be honest.

> P.S. I am still waiting for you to come back regarding the license topic. Please do not take too much time to consider it.

Yes. This is a very difficult decision for me to make. I've had a lot of distractions recently (I am starting a PhD soon, and need to get a bunch of things in order beforehand) and put this decision off. I'll have an answer before this week is over, I promise!
