### ISSUE TITLE
Checking for EndOfFile

### ISSUE THREAD

**Issue by ythri** [AntonLydike/filecheck#23]
Hey,

I've upgraded from the discontinued `mull-project/FileCheck.py` 0.0.24 to this one, and now get quite a few errors. One cause is that I use CHECK-EMPTY to test that no more lines occur; e.g. for a file consisting of two lines with content "a" and "b" and a final line break (e.g., `a\nb\n`), I might have a test with 
```
CHECK: a
CHECK-NEXT: b
CHECK-EMPTY:
```
to make sure that there is no further line after b (or if there is, it is empty).

This test used to work in `mull-project/FileCheck.py`, but results in a failed test now, as it now inteprets the last line break not as a new empty line.

So, do you know which behavior is the correct one? Is this a bug in your implementation, or was the discontinued implementation by mull-project non-comforming? Do you have any suggestions on how to change the test to (explicitely) check for EOF?

Thanks for your work!

**Comment by AntonLydike** [comment]
I can confirm, `FileCheck` passes this, but we don't:

```
// RUN: strip-comments.sh %s | filecheck %s
test
// CHECK: test
// CHECK-EMPTY:
```

Will work on a fix!

**Comment by AntonLydike** [comment]
Allright, I have a fix ready. Although I'm afraid that `CHECK-EMPTY` can't be used to verify that there is nothing left in the file, as there might be an empty line, and *then* some more text.

I would suggest you use `CHECK-NOT: {{\S+}}` instead, which checks that there are no non-space characters left on any line.

**Comment by AntonLydike** [comment]
Thanks for raising this issue! Please let me know if you run into any other problems!

Also, if in case your project is open source, I'm happy to take a quick look and see what else fails. I'm always looking for more data points!

**Comment by ythri** [comment]
Wow, thank you so much on the super quick investigation and fix!

Sadly, my code is closed source. But I will try the new version and see if there are still failing tests and give you feedback.

Again, thank you so much!
