### ISSUE TITLE
check-prefix being a suffix of other check-prefixes in the same file

### ISSUE THREAD

**Issue by ythri** [AntonLydike/filecheck#28]
Hi,

here is the second issue I found, where filecheck behaves differently from the official LLVM FileCheck.

In my project, I sometimes have multiple tests in the same file, like this:
```
RUN: echo "1" | filecheck %s --check-prefix FIRST
FIRST: 1

RUN: echo "2" | filecheck %s --check-prefix SECOND
SECOND: 2
```

This works completely fine. However, once one of the check-prefixes is a suffix of another check-prefix, filecheck want to check both, while LLVM FileCheck still works correctly.

I.e., if I change the test to
```
RUN: echo "1" | filecheck %s --check-prefix TEST
TEST: 1

RUN: echo "2" | filecheck %s --check-prefix SECONDTEST
SECONDTEST: 2
```
then filecheck fails with:
```
$ echo "1" | filecheck test.itest --check-prefix TEST
test3.itest:5: error: Couldn't match "2".
Current position at <stdin>:1:1

^
```
while LLVM FileCheck correctly sees SECONDTEST as a different prefix from TEST.

This can be relevant e.g. if you have tests like "INT_TEST" and "UINT_TEST" :)

**Comment by AntonLydike** [comment]
Interesting! I had briefly considered that interaction previously, but didn't check how LLVM did it. I'll look into LLVM to see how they decide what a prefix actually is!
